---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен иметь мобильную версию
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Поиск по ключевым словам должен быть регистронезависимым
  - При переходе по страницам магазина страница не должна перезагружаться
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность очищать данные корзины
  - Пользователь должен иметь возможность оформить заказ
  - При перезагрузке страницы товары в корзине должны оставаться
  - При удалении данных корзины и перезагрузке страницы корзина должна быть пустой
  - Пользователь может выйти из корзины для продолжения покупок, данные корзины сохраняются
  - Мобильная версия сайта имеет адаптивный дизайн
  - Сайт должен быстро загружаться на сетях, со скоростью 3G (3.5 Mbps)
  - Пользователь не может добавить в корзину больше единиц товара, чем доступно