---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен иметь мобильную версию
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быстро загружаться на сетях, со скоростью 3G (3.5 Mbps)
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность очищать данные корзины
  - Пользователь должен иметь возможность редактировать количество товаров в корзине
  - При перезагрузке страницы товары в корзине должны оставаться
  - При удалении данных корзины и перезагрузке страницы корзина должна быть пустой
  - На сайте не должно быть битых ссылок
  - Пользователь может выбрать нужно число товаров на этапе добавления товара в корзину
  - Если пользователь ввел число товаров, превышающее количество товара, выводится предупреждение и товар не добавляется
  - Пользователь может выйти из корзины для продолжения покупок, данные корзины сохраняются
  - При переключении языка интерфейса на английский язык, все пункты меню и названия товаров отображаются на английском
  - Сайт должен быть неуязвим для XSS-атак и SQL-инъекций
  - У покупателя не должно быть прав администратора
  - Мобильная версия сайта имеет адаптивный дизайн
  - Сайт должен выдержать заход 10000 пользователей одновременно
  - Сайт должен быть доступен на мобильных телефонах, планшетах и десктопных компьютерах
  - Сайт должен работать в последних версиях браузеров Safari, Chrome, Firefox
  - При добавлении товара в корзину должно отображаться модальное окно, что товар был добавлен в корзину
  - При клике на оформление заказа запрос успешно отсылается на сервер
  - У пользователя должна быть возможность управлять созданными заказами
